# Generated by Django 4.1.6 on 2023-02-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
